version: '3.7'
services:
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: reddit_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reddit-stream

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: reddit_zookeeper
    platform: linux/arm64/v8
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - reddit-stream

  spark:
    image: bitnami/spark:latest
    container_name: reddit_spark
    depends_on:
      - kafka
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
    volumes:
      - ./spark_jobs:/opt/spark/jobs
      - ./python_app/jars:/opt/spark/jars
    ports:
      - "8080:8080"
    networks:
      - reddit-stream

  cassandra:
    image: cassandra:latest
    container_name: reddit_cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_START_RPC: 'true'
    networks:
      - reddit-stream

  grafana:
    image: grafana/grafana:latest
    container_name: reddit_grafana
    depends_on:
      - cassandra
    ports:
      - "3000:3000"
    networks:
      - reddit-stream

  ingestor:
    build: ./ingestion
    container_name: reddit_ingestor
    depends_on:
      - kafka
    environment:
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${REDDIT_CLIENT_SECRET}
      REDDIT_USER_AGENT: ${REDDIT_USER_AGENT}
      KAFKA_BROKER: ${KAFKA_BROKER}
      TOPIC_NAME: ${TOPIC_NAME}
    restart: unless-stopped
    networks:
        - reddit-stream

networks:
  reddit-stream:
    driver: bridge